spring:
  application:
    name: api-playground
  shell:
    interactive:
      enabled: true
  main:
    web-application-type: none
  security:
    oauth2:
      client:
        registration:
          test-login:
            client-id: placeholder
            client-secret: placeholder
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8080/api/auth/redirect
        provider:
          test-login:
            authorization-uri: ${test.uri}/api/auth/authorize
            token-uri: ${test.uri}/api/auth/token
test:
  uri: http://localhost:8080
  client-logname: placeholder
  client-password: placeholder
  login-uri: ${test.uri}/api/auth/login
